# Generated by Django 5.0.2 on 2024-04-07 13:22

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_basket_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.upload_product_preview),
        ),
    ]
